@startuml


actor 従業員
note left
### 基本コース
システムは「ログイン」ページを表示する。
従業員はメールアドレスフィールド、パスワードフィールドに自身のアカウントの沿った情報を入力し、「ログイン」ボタンをクリックする。
システムはメールアドレスから従業員アカウントを取得し、パスワードの照合をする。その後、「ダッシュボード」ページを表示する

### 代替コース
従業員アカウントが見つからない：「メールアドレスかパスワードが間違っています」というテキストを表示する
パスワードが正しくない：「メールアドレスかパスワードが間違っています」というテキストを表示する
end note
boundary "「ログイン」ページ" as loginPage
entity マスターアカウントリスト
entity 従業員アカウント
control "「ログイン」ページを表示する" as showLoginPage
control メールアドレスとパスワードを入力する
control 従業員アカウントは存在するか
control 従業員アカウント情報を取得する
control パスワードは正しいか
control "「メールアドレスまたはパスワードが間違っています」を表示する" as loginErrorMessage #ccc
control 認証済みのセッションを開始する
control "直前のページを表示する" as showLastPage




従業員 - loginPage
showLoginPage --> loginPage
loginPage -> メールアドレスとパスワードを入力する
メールアドレスとパスワードを入力する -> 従業員アカウントは存在するか : 「ログイン」ボタンをクリック
従業員アカウントは存在するか - マスターアカウントリスト
マスターアカウントリスト -> 従業員アカウント情報を取得する
従業員アカウント情報を取得する - 従業員アカウント
従業員アカウントは存在するか --> パスワードは正しいか : はい
従業員アカウントは存在するか --> loginErrorMessage : いいえ
パスワードは正しいか --> loginErrorMessage : いいえ
パスワードは正しいか -> 認証済みのセッションを開始する : はい
認証済みのセッションを開始する - showLastPage
loginErrorMessage -> loginPage

@enduml