@startuml ユースケース
left to right direction

:従業員:

rectangle {

:従業員: ..> (勤怠予定を登録する)
:従業員: ..> (営業予定を登録する)
(営業予定を登録する) ..> (顧客を営業予定に登録する) : <<invokes>>
(営業予定を登録する) ..> (営業報告を登録する) : <<invokes>>
:従業員: ..> (顧客を登録する)
:従業員: ..> (メッセージを送信する)
:従業員: ..> (メッセージを閲覧する)

}

:管理者:

rectangle {
(営業報告を登録する) .left.> (営業結果にコメントする) : <<precedes>>
:管理者: ..> (営業結果にコメントする)
:管理者: ..> (従業員アカウントを登録する)
:管理者: ..> (従業員の勤怠予定を閲覧する)
:管理者: ..> (従業員の営業予定を閲覧する)
 (従業員の勤怠予定を閲覧する) ..> (従業員へメッセージを送る) : <<invokes>>
 (従業員の営業予定を閲覧する) ..> (従業員へメッセージを送る) : <<invokes>>
}

@enduml