@startuml ユースケース
left to right direction

:従業員:

(ログインする)

rectangle ログイン後{
(ログアウトする)
(勤怠予定を登録する)
(勤怠予定を編集する)
(勤怠予定を削除する)
(出勤日時を登録する)
(退勤日時を登録する)
(営業予定を登録する)
(営業予定を編集する)
(営業予定を削除する)
(顧客を営業予定に登録する)
(顧客を営業予定から削除する)
(営業報告を登録する)
(営業報告を編集する)
(営業報告を削除する)
(顧客を登録する)
(顧客を編集する)
(顧客を削除する)
(メッセージを送信する)
(メッセージを削除する)
(メッセージを閲覧する)

(メッセージを閲覧する) ..> (メッセージを送信する) : <<invokes>>
(営業予定を登録する) ..> (顧客を営業予定に登録する) : <<precedes>>
(営業予定を登録する) ..> (営業報告を登録する) : <<precedes>>

}
(ログインする) --> ログイン済み : <<precedes>>

@enduml