@startuml ユースケース
left to right direction

:管理者:

rectangle ログイン後 {

(営業結果にコメントする)
(コメントを編集する)
(コメントを削除する)
(従業員アカウントを作成する)
(従業員アカウントを削除する)
(従業員の勤怠予定を閲覧する)
(従業員の営業予定を閲覧する)

(営業報告を登録する) ..> (営業結果にコメントする) : <<precedes>>
(従業員の勤怠予定を閲覧する) ..> (従業員へメッセージを送る) : <<invokes>>
(従業員の営業予定を閲覧する) .> (従業員へメッセージを送る) : <<invokes>>
}

(ログインする) --> ログイン後 : <<precedes>>
@enduml