# This workflow will do a clean install of node dependencies, test the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Reg suit

on:
  push:
    branches: [master]
  pull_request:
    paths: ["doc/**"]

jobs:
  reg-suit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      # キャッシュ管理
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # /キャッシュ管理
      - run: sudo apt-get install fonts-migmix graphviz
      - run: yarn install
      - name: Reg Suit Test
        run: yarn run-reg-suit
        env:
          CLIENT_ID_FOR_REGSUIT: ${{ secrets.CLIENT_ID_FOR_REGSUIT }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
